### ISSUE TITLE
Please consider updating the Java example because it is rather dated.

### ISSUE THREAD

**Issue by bruce-forte** [howtographql/graphql-java#5]
The Java example uses Maven and Servlets. Both are rather dated tools but the main problem is that it uses Maven archetypes for example which are not present when using other tools like Gradle.

Most example projects of other libraries use Spring for example since it is the most popular framework of choice and it is also a common practice to give Maven **and** Gradle examples and don't use build tool specific features (like archetypes).

Is there a chance that this can be improved?

**Comment by xetra11** [comment]
I cannot follow the tutorial because my Graph QL Java version is 8 and the whole API kinda changed :/ hard time to adapt everything to the new API
